version: '3.8'

services:
  ai-storyline-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-storyline-generator
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      # Mount your API key via environment variable
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      # Frontend URL not needed in production since we serve static files
    restart: unless-stopped
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    # Optional: limit resources
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
